### ISSUE TITLE
MSRV violated by dependencies

### ISSUE THREAD

**Issue by 9names** [ilya-epifanov/riscv-target#2]
This crate has a listed MSRV of 1.30, but the effective MSRV is currently 1.65 because the regex dependency is effectively unconstrained.

```toml
[dependencies]
regex = "1"
lazy_static = "1"
```

**Comment by ilya-epifanov** [comment]
Well, I can't constrain it. Even trying to pin the version to `<=1.1` or something similar doesn't help. I guess in the context of a library MSRV of transitive dependencies doesn't mean much.

**Comment by 9names** [comment]
Yeah. I think this is a limitation of Cargo that we just have to live with. And maybe it is best to be unconstrained here, so the end user can constrain in the dependent crate(s).
I've pinned the following dependencies in mine to bring the MSRV back down:
```toml
regex = "=1.8.4"
memchr = "=2.5.0"
```

The riscv crate has [it's own implementation](https://github.com/rust-embedded/riscv/blob/3cfade537c0bf00078cd24ddb7ac833dfbd8ea7e/riscv-rt/build.rs#L21) of this functionality for it's purposes.
Having thought about it a bit more since raising this issue, and having looked at the current ISA naming convention docs,  I think I'll probably end up writing my own parser for that anyway.

Going to close this since I think documenting the deps to pin is the best answer at this point.
Apologies for the noise.
